# -*- coding: utf-8 -*-
"""GeneticAlgorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKXeuwE4XLC3vkavXTRG2HS8jMvPYNA4

***GENETIC ALGORITHM***
"""

import yfinance as yf
import numpy as np
import pandas as pd
import time
import random

# Fixed GA hyperparameters
N_POPULATION = 100
N_GENERATIONS = 150
MUTATION_RATE = 0.15
CROSSOVER_RATE = 0.8
RISK_FREE_RATE = 0.02
TRAIN_RATIO = 0.8

def evaluate_portfolio(weights, returns, risk_free_rate):
    daily_port_returns = returns @ weights
    mean_return = np.mean(daily_port_returns) * 252
    variance = np.var(daily_port_returns) * 252
    volatility = np.std(daily_port_returns) * np.sqrt(252)
    sharpe_ratio = (mean_return - risk_free_rate) / volatility
    cumulative_returns = (1 + daily_port_returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    max_drawdown = drawdown.min()
    return {
        'Mean Return': mean_return,
        'Variance': variance,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': max_drawdown
    }

class GeneticAlgorithm:
    def __init__(self, n_population, n_generations, mutation_rate, crossover_rate, tickers, risk_free_rate):
        self.n_population = n_population
        self.n_generations = n_generations
        self.mutation_rate = mutation_rate
        self.crossover_rate = crossover_rate
        self.tickers = tickers
        self.risk_free_rate = risk_free_rate
        self.n_assets = len(tickers)
        self.population = np.random.random((n_population, self.n_assets))
        self.best_sharpe_ratio = -np.inf
        self.best_portfolio = None

    def normalize_population(self):
        self.population = self.population / np.sum(self.population, axis=1)[:, None]

    def fitness(self, portfolio, returns):
        return evaluate_portfolio(portfolio, returns, self.risk_free_rate)['Sharpe Ratio']

    def select_parents(self):
        tournament_size = 3
        selected_indices = []
        for _ in range(2):
            tournament_indices = np.random.choice(range(self.n_population), size=tournament_size, replace=False)
            tournament_fitness = np.array([self.fitness(self.population[i], self.train_returns) for i in tournament_indices])
            winner_idx = tournament_indices[np.argmax(tournament_fitness)]
            selected_indices.append(winner_idx)
        return self.population[selected_indices]

    def crossover(self, parent1, parent2):
        if np.random.rand() < self.crossover_rate:
            crossover_point = np.random.randint(1, self.n_assets)
            child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
            child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
            return child1, child2
        else:
            return parent1, parent2

    def mutate(self, portfolio):
        if np.random.rand() < self.mutation_rate:
            mutation_point = np.random.randint(self.n_assets)
            portfolio[mutation_point] = np.random.rand()
            portfolio /= np.sum(portfolio)
        return portfolio

    def evolve(self, train_returns):
        self.train_returns = train_returns
        self.normalize_population()
        elite_size = 5
        for generation in range(self.n_generations):
            fitness_values = np.array([self.fitness(p, train_returns) for p in self.population])
            sorted_indices = np.argsort(fitness_values)[::-1]
            self.population = self.population[sorted_indices]
            elite = self.population[:elite_size].copy()

            print(f"Generation {generation+1}: Best Sharpe Ratio = {fitness_values[sorted_indices[0]]:.4f}")

            new_population = []
            while len(new_population) < self.n_population - elite_size:
                parent1, parent2 = self.select_parents()
                child1, child2 = self.crossover(parent1, parent2)
                new_population.append(self.mutate(child1))
                new_population.append(self.mutate(child2))

            self.population = np.vstack([elite, np.array(new_population)])
            best_fitness = fitness_values[sorted_indices[0]]
            if best_fitness > self.best_sharpe_ratio:
                self.best_sharpe_ratio = best_fitness
                self.best_portfolio = self.population[0]

        return self.best_portfolio

def run_ga_for_scenario(tickers, start_date, label):
    data = yf.download(tickers, start=start_date, end='2024-12-31')['Close'].dropna()
    returns = data.pct_change().dropna()
    split_index = int(len(returns) * TRAIN_RATIO)
    train_returns = returns.iloc[:split_index]
    test_returns = returns.iloc[split_index:]

    start = time.time()
    optimizer = GeneticAlgorithm(N_POPULATION, N_GENERATIONS, MUTATION_RATE, CROSSOVER_RATE, tickers, RISK_FREE_RATE)
    best_portfolio = optimizer.evolve(train_returns)
    end = time.time()

    metrics = evaluate_portfolio(best_portfolio, test_returns, RISK_FREE_RATE)
    metrics['Computation Time (s)'] = end - start
    metrics['Scenario'] = label

    if label == '5Y - 5 Stocks':
        print("\nSharpe Ratio Per Year (5Y - 5 Stocks):")
        for year in range(2019, 2024):
            yearly_data = returns[(returns.index >= f'{year}-01-01') & (returns.index < f'{year+1}-01-01')]
            if not yearly_data.empty:
                yearly_sharpe = evaluate_portfolio(best_portfolio, yearly_data, RISK_FREE_RATE)['Sharpe Ratio']
                print(f"{year}-01-01 to {year+1}-01-01 Sharpe Ratio: {yearly_sharpe:.4f}")
            else:
                print(f"{year}-01-01 to {year+1}-01-01: Not enough data")

    return metrics

# === Scenario Definitions (updated labels and tickers) ===
scenarios = [
    ('Base Case: 5Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01'),
    ('Time Comparison: 15Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2009-01-01'),
    ('Stock Comparison: 5Y - 10 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'MSFT', 'TSLA', 'NVDA', 'XOM', 'PG'], '2019-01-01')
]


# === Run All Scenarios ===
results = [run_ga_for_scenario(tickers, start_date, label) for label, tickers, start_date in scenarios]

# === Convert Results to DataFrame and Print ===
df = pd.DataFrame(results)
print("\n\n=== Genetic Algorithm Portfolio Optimization Results ===")
print(df[['Scenario', 'Mean Return', 'Variance', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']].round(4).to_string(index=False))