# -*- coding: utf-8 -*-
"""Heuristic Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBcXibNClCpV8zmFaWpqxvxFXUCmKHbG

ANT COLONY OPTIMISATION (ACO)
"""

import yfinance as yf
import numpy as np
import pandas as pd
import time
import random
from scipy.optimize import minimize

# ======================== CONFIG ========================
RISK_FREE_RATE = 0.02
TRAIN_RATIO = 0.8
N_ANTS = 100
N_ITERATIONS = 500
ALPHA = 1.0
BETA = 2.0
EVAPORATION_RATE = 0.1

# ======================== EVALUATION ========================
def evaluate_portfolio(weights, returns, risk_free_rate):
    daily_port_returns = returns @ weights
    mean_return = np.mean(daily_port_returns) * 252
    variance = np.var(daily_port_returns) * 252
    volatility = np.std(daily_port_returns) * np.sqrt(252)
    sharpe_ratio = (mean_return - risk_free_rate) / volatility
    cumulative_returns = (1 + daily_port_returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    max_drawdown = drawdown.min()
    return {
        'Mean Return': mean_return,
        'Variance': variance,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': max_drawdown
    }

# ======================== ACO CLASS ========================
class AntColony:
    def __init__(self, n_ants, n_iterations, alpha, beta, evaporation_rate, tickers, risk_free_rate):
        self.n_ants = n_ants
        self.n_iterations = n_iterations
        self.alpha = alpha
        self.beta = beta
        self.evaporation_rate = evaporation_rate
        self.tickers = tickers
        self.risk_free_rate = risk_free_rate
        self.n_assets = len(tickers)
        self.pheromone = np.ones(self.n_assets)
        self.best_sharpe_ratio = -np.inf
        self.best_portfolio = None

    def generate_portfolio(self):
        weights = self.pheromone * np.random.rand(self.n_assets)
        weights /= np.sum(weights)
        return weights

    def update_pheromone(self, portfolio, sharpe_ratio):
        for i in range(self.n_assets):
            self.pheromone[i] = (1 - self.evaporation_rate) * self.pheromone[i] + self.alpha * sharpe_ratio

    def optimize(self, train_returns):
        print(f">>> Starting ACO optimization: {self.n_ants} ants × {self.n_iterations} iterations")
        for it in range(self.n_iterations):
            best_iter_sharpe = -np.inf
            best_iter_portfolio = None
            for ant in range(self.n_ants):
                portfolio = self.generate_portfolio()
                metrics = evaluate_portfolio(portfolio, train_returns, self.risk_free_rate)
                if metrics['Sharpe Ratio'] > best_iter_sharpe:
                    best_iter_sharpe = metrics['Sharpe Ratio']
                    best_iter_portfolio = portfolio
            self.update_pheromone(best_iter_portfolio, best_iter_sharpe)
            if best_iter_sharpe > self.best_sharpe_ratio:
                self.best_sharpe_ratio = best_iter_sharpe
                self.best_portfolio = best_iter_portfolio

            if (it + 1) % 50 == 0 or it == 0:
                print(f"Iteration {it+1}: Best Sharpe so far = {self.best_sharpe_ratio:.4f}")
        return self.best_portfolio

# ======================== RUN FUNCTION ========================
def run_aco_for_scenario(tickers, start_date, label):
    print(f"\nRunning ACO for {label}")
    data = yf.download(tickers, start=start_date, end='2024-12-31')['Close']
    data = data.dropna()
    returns = data.pct_change().dropna()

    print(f"Downloaded data from {data.index[0].date()} to {data.index[-1].date()}")
    print(f"Total days of returns: {len(returns)}")

    split_index = int(len(returns) * TRAIN_RATIO)
    train_returns = returns.iloc[:split_index]
    test_returns = returns.iloc[split_index:]

    print(f"Train range: {train_returns.index[0].date()} to {train_returns.index[-1].date()}")
    print(f"Test range : {test_returns.index[0].date()} to {test_returns.index[-1].date()}")

    start_time = time.time()
    optimizer = AntColony(N_ANTS, N_ITERATIONS, ALPHA, BETA, EVAPORATION_RATE, tickers, RISK_FREE_RATE)
    best_portfolio = optimizer.optimize(train_returns)
    end_time = time.time()

    metrics = evaluate_portfolio(best_portfolio, test_returns, RISK_FREE_RATE)
    metrics['Computation Time (s)'] = end_time - start_time
    metrics['Scenario'] = label

    # =========== Print Per-Year Sharpe for 5Y - 5 Stocks ===========
    if label == '5Y - 5 Stocks':
        print("\nSharpe Ratio Per Year (5Y - 5 Stocks):")
        for year in range(2019, 2024):
            year_data = returns[(returns.index >= f'{year}-01-01') & (returns.index < f'{year+1}-01-01')]
            if not year_data.empty:
                yearly_sharpe = evaluate_portfolio(best_portfolio, year_data, RISK_FREE_RATE)['Sharpe Ratio']
                print(f"{year}-01-01 to {year+1}-01-01 Sharpe Ratio: {yearly_sharpe:.4f}")
            else:
                print(f"{year}-01-01 to {year+1}-01-01: Not enough data")

    return metrics

# ======================== EXECUTE ALL 3 ========================
results = []
results.append(run_aco_for_scenario(['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01', 'Base Case: 5Y - 5 Stocks'))
results.append(run_aco_for_scenario(['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2009-01-01', 'Time Comparison: 15Y - 5 Stocks'))
results.append(run_aco_for_scenario(['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'MSFT', 'TSLA', 'NVDA', 'XOM', 'PG'], '2019-01-01', 'Stock Comparison: 5Y - 10 Stocks'))

# ======================== DISPLAY ========================
results_df = pd.DataFrame(results)
print("\n\n=== ACO Results ===")
print(results_df[['Scenario', 'Mean Return', 'Variance', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']].round(4).to_string(index=False))