# -*- coding: utf-8 -*-
"""Mean Variance Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1JvTU1LNimGkqPBtqrvCC_T_6EEqsC8

***MEAN VARIANCE OPTIMISATION ALGORITHM***
"""

import yfinance as yf
import numpy as np
import pandas as pd
from scipy.optimize import minimize
import time

# Hyperparameters
RISK_FREE_RATE = 0.02
TRAIN_TEST_SPLIT = 0.8
OPTIMIZATION_METHOD = 'SLSQP'
MAX_WEIGHT = 1.0

# === Scenario Definitions (aligned with GA, ACO, DQN) ===
scenarios = [
    ('Base Case: 5Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01'),
    ('Time Comparison: 15Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2009-01-01'),
    ('Stock Comparison: 5Y - 10 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'MSFT', 'TSLA', 'NVDA', 'XOM', 'PG'], '2019-01-01')
]

# === Portfolio Evaluation ===
def evaluate_portfolio(weights, returns, risk_free_rate):
    daily_port_returns = returns @ weights
    mean_return = np.mean(daily_port_returns) * 252
    variance = np.var(daily_port_returns) * 252
    volatility = np.std(daily_port_returns) * np.sqrt(252)
    sharpe_ratio = (mean_return - risk_free_rate) / volatility
    cumulative_returns = (1 + daily_port_returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    max_drawdown = drawdown.min()
    return {
        'Mean Return': mean_return,
        'Variance': variance,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': max_drawdown
    }

# === Mean-Variance Optimization ===
def mean_variance_optimization(train_returns):
    n = train_returns.shape[1]
    mean_returns = train_returns.mean() * 252
    cov_matrix = train_returns.cov() * 252

    def objective(weights):
        return -((weights @ mean_returns - RISK_FREE_RATE) / np.sqrt(weights @ cov_matrix @ weights.T))

    constraints = {'type': 'eq', 'fun': lambda x: np.sum(x) - 1}
    bounds = [(0.0, MAX_WEIGHT) for _ in range(n)]
    init_guess = np.ones(n) / n

    start = time.time()
    result = minimize(objective, init_guess, method=OPTIMIZATION_METHOD, bounds=bounds, constraints=constraints)
    end = time.time()

    return result.x, end - start

# === Scenario Runner ===
results = []
five_year_weights = None
five_year_returns_all = None

def run_mean_variance_for_scenario(label, tickers, start_date):
    global five_year_weights, five_year_returns_all
    print(f"\nRunning scenario: {label}")
    data = yf.download(tickers, start=start_date, end='2024-12-31')['Close'].dropna()
    returns = data.pct_change().dropna()
    split_index = int(TRAIN_TEST_SPLIT * len(returns))
    train_returns = returns.iloc[:split_index]
    test_returns = returns.iloc[split_index:]

    weights, comp_time = mean_variance_optimization(train_returns)
    metrics = evaluate_portfolio(weights, test_returns, RISK_FREE_RATE)
    metrics['Computation Time (s)'] = comp_time
    metrics['Scenario'] = label

    if label == 'Base Case: 5Y - 5 Stocks':
        five_year_weights = weights
        five_year_returns_all = returns

    return metrics

# === Run and store results ===
for label, tickers, start_date in scenarios:
    results.append(run_mean_variance_for_scenario(label, tickers, start_date))

df = pd.DataFrame(results)

# === Print main table ===
print("\nMean-Variance Portfolio Optimization Results:\n")
print(df[['Scenario', 'Mean Return', 'Variance', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']].round(4).to_string(index=False))

# === Yearly Sharpe Ratios (Base Case only) ===
if five_year_weights is not None and five_year_returns_all is not None:
    print("\nSharpe Ratio Per Year (Base Case: 5Y - 5 Stocks):")
    years = ['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01', '2024-01-01']
    for i in range(len(years) - 1):
        yearly_data = five_year_returns_all.loc[years[i]:years[i+1]]
        if not yearly_data.empty and len(yearly_data) > 1:
            daily_port_returns = yearly_data @ five_year_weights
            ann_return = np.mean(daily_port_returns) * 252
            ann_vol = np.std(daily_port_returns) * np.sqrt(252)
            if ann_vol != 0:
                sharpe = (ann_return - RISK_FREE_RATE) / ann_vol
                print(f"{years[i]} to {years[i+1]} Sharpe Ratio: {sharpe:.4f}")
            else:
                print(f"{years[i]} to {years[i+1]} Sharpe Ratio: N/A (zero volatility)")
        else:
            print(f"{years[i]} to {years[i+1]}: Not enough data")