# -*- coding: utf-8 -*-
"""Reinforcement Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpJmOyIyWiwEZXkDg_TWV6-Wqf8R5nzw

**REINFORCEMENT LEARNING**
"""

import yfinance as yf
import numpy as np
import pandas as pd
import time
import random
from collections import deque
import tensorflow as tf
from tensorflow.keras import layers


# ==== CONFIGURATION ====
TICKERS = ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'MSFT', 'TSLA', 'NVDA', 'XOM', 'PG']
TRAIN_RATIO = 0.7
EPISODES = 50
GAMMA = 0.99
EPSILON = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.995
BATCH_SIZE = 64
MEMORY_SIZE = 1000
PATIENCE = 30  # Early stopping patience

# ==== DATA ====
def download_returns(tickers, start, end):
    data = yf.download(tickers, start=start, end=end)['Close'].dropna()
    returns = data.pct_change().dropna()
    returns = returns[::2]  # every 2nd day
    return returns

def split_data(returns):
    total_len = len(returns)
    train_split = int(total_len * 0.6)
    val_split = int(total_len * 0.8)
    train = returns.iloc[:train_split]
    val = returns.iloc[train_split:val_split]
    test = returns.iloc[val_split:]
    return train, val, test

# ==== ENVIRONMENT ====
class PortfolioEnv:
    def __init__(self, returns):
        self.returns = returns.values
        self.n_assets = self.returns.shape[1]
        self.max_steps = len(self.returns) - 1
        self.reset()

    def reset(self):
        self.current_step = 0
        return self._normalize(self.returns[self.current_step])

    def step(self, action_weights):
        self.current_step += 1
        self.weights = np.clip(action_weights, 0, 1)
        self.weights /= np.sum(self.weights)
        reward = np.dot(self.returns[self.current_step], self.weights)
        done = self.current_step >= self.max_steps
        return self._normalize(self.returns[self.current_step]), reward, done

    def _normalize(self, x):
        return (x - np.mean(x)) / (np.std(x) + 1e-8)

# ==== DQN AGENT ====
class DQNAgent:
    def __init__(self, n_assets):
        self.n_assets = n_assets
        self.memory = deque(maxlen=MEMORY_SIZE)
        self.model = self._build_model()
        self.epsilon = EPSILON

    def _build_model(self):
        model = tf.keras.Sequential([
            layers.Input(shape=(self.n_assets,)),
            layers.Dense(128, activation='relu'),
            layers.Dense(64, activation='relu'),
            layers.Dense(self.n_assets, activation='softmax')
        ])
        model.compile(optimizer='adam', loss='mse')
        return model

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return np.random.dirichlet(np.ones(self.n_assets))
        return self.model.predict(np.expand_dims(state, axis=0), verbose=0)[0]

    def remember(self, state, action, reward, next_state):
        self.memory.append((state, action, reward, next_state))

    def replay(self):
        if len(self.memory) < BATCH_SIZE: return
        batch = random.sample(self.memory, BATCH_SIZE)
        states = np.array([b[0] for b in batch])
        next_states = np.array([b[3] for b in batch])
        targets = self.model.predict(states, verbose=0)
        next_qs = self.model.predict(next_states, verbose=0)
        for i, (state, action, reward, next_state) in enumerate(batch):
            targets[i] = action * (reward + GAMMA * np.max(next_qs[i]))
        self.model.fit(states, targets, epochs=1, verbose=0)

# ==== TRAINING WITH EARLY STOPPING ====
def train_agent(train_returns, val_returns):
    env = PortfolioEnv(train_returns)
    val_env = PortfolioEnv(val_returns)
    agent = DQNAgent(env.n_assets)

    best_val_sharpe = -np.inf
    best_weights = None
    no_improve = 0

    for episode in range(EPISODES):
        # --- training ---
        state = env.reset()
        done = False
        rewards = []

        while not done:
            action = agent.act(state)
            next_state, reward, done = env.step(action)
            agent.remember(state, action, reward, next_state)
            agent.replay()
            state = next_state
            rewards.append(reward)

        # --- validation ---
        val_rewards = []
        state = val_env.reset()
        done = False
        while not done:
            action = agent.act(state)
            state, reward, done = val_env.step(action)
            val_rewards.append(reward)

        val_sharpe = (np.mean(val_rewards) * 252) / (np.std(val_rewards) * np.sqrt(252) + 1e-8)

        print(f"Episode {episode+1}: Val Sharpe = {val_sharpe:.4f} | Best = {best_val_sharpe:.4f} | No Improve = {no_improve}")

        if val_sharpe > best_val_sharpe:
            best_val_sharpe = val_sharpe
            best_weights = agent.model.get_weights()
            no_improve = 0
        else:
            no_improve += 1

        if no_improve >= PATIENCE:
            print("🛑 Early stopping on validation set.")
            break

        if agent.epsilon > EPSILON_MIN:
            agent.epsilon *= EPSILON_DECAY

    if best_weights:
        agent.model.set_weights(best_weights)
    return agent

# ==== EVALUATION ====
def evaluate(agent, returns):
    env = PortfolioEnv(returns)
    state = env.reset()
    done = False
    port_returns = []

    while not done:
        action = agent.act(state)
        state, reward, done = env.step(action)
        port_returns.append(reward)

    port_returns = np.array(port_returns)
    cumulative = (1 + port_returns).cumprod()
    ann_return = np.mean(port_returns) * 252
    ann_vol = np.std(port_returns) * np.sqrt(252)
    sharpe = ann_return / (ann_vol + 1e-8)
    max_dd = (np.min(cumulative / np.maximum.accumulate(cumulative)) - 1)

    print("\n Final Evaluation:")
    print(f"Mean Return     : {ann_return:.4f}")
    print(f"Volatility      : {ann_vol:.4f}")
    print(f"Sharpe Ratio    : {sharpe:.4f}")
    print(f"Max Drawdown    : {max_dd:.4f}")
    return {
        "Mean Return": ann_return,
        "Volatility": ann_vol,
        "Sharpe Ratio": sharpe,
        "Max Drawdown": max_dd
    }

# ==== SCENARIO WRAPPER ====
def run_dqn_scenario(tickers, start_date, label):
    print(f"\n==== Running DQN for Scenario: {label} ====")
    returns = download_returns(tickers, start=start_date, end='2024-01-01')
    train_returns, val_returns, test_returns = split_data(returns)
    agent = train_agent(train_returns, val_returns)
    metrics = evaluate(agent, test_returns)
    metrics['Scenario'] = label
    return metrics

# ==== MAIN ====
if __name__ == "__main__":
    scenarios = [
        ('Base Case: 5Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01'),
        ('Time Comparison: 15Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2009-01-01'),
        ('Stock Comparison: 5Y - 10 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'MSFT', 'TSLA', 'NVDA', 'XOM', 'PG'], '2019-01-01')
    ]

    results = [run_dqn_scenario(tickers, start_date, label) for label, tickers, start_date in scenarios]
    df = pd.DataFrame(results)

    print("\n\n=== DQN Portfolio Optimization Results ===")
    print(df[['Scenario', 'Mean Return', 'Volatility', 'Sharpe Ratio', 'Max Drawdown']].round(4).to_string(index=False))