# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f077p2y7dXXWSSSZO-QOE9waR5CDYf4Y
"""

# -*- coding: utf-8 -*-
"""Portfolio Optimization Comparison"""

import yfinance as yf
import numpy as np
import pandas as pd
import time

# Import all algorithm implementations
from mean_variance_optimization import run_mean_variance_for_scenario
from geneticalgorithm import run_ga_for_scenario
from heuristic_model import run_aco_for_scenario
from reinforcement_learning import run_dqn_scenario

# ======================== CONFIGURATION ========================
RISK_FREE_RATE = 0.02
TRAIN_TEST_SPLIT = 0.8
BENCHMARK = '^GSPC'  # S&P 500 benchmark
START_DATE = '2019-01-01'
END_DATE = '2024-01-01'

# Only keep the Base Case scenario
SCENARIOS = [
    ('Base Case: 5Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01')
]

# ======================== BENCHMARK CODE ========================
def evaluate_portfolio(weights, returns, risk_free_rate):
    """Evaluate portfolio performance metrics"""
    daily_port_returns = returns @ weights
    mean_return = np.mean(daily_port_returns) * 252
    variance = np.var(daily_port_returns) * 252
    volatility = np.std(daily_port_returns) * np.sqrt(252)
    sharpe_ratio = (mean_return - risk_free_rate) / (volatility + 1e-8)
    cumulative_returns = (1 + daily_port_returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    return {
        'Mean Return': mean_return,
        'Variance': variance,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': drawdown.min()
    }

def run_benchmark():
    """Run benchmark (S&P 500) analysis"""
    print("\nDownloading S&P 500 benchmark data...")
    benchmark_data = yf.download(BENCHMARK, start=START_DATE, end=END_DATE)['Close'].dropna()
    benchmark_returns = benchmark_data.pct_change().dropna()
    split_idx = int(len(benchmark_returns) * TRAIN_TEST_SPLIT)
    test_returns = benchmark_returns.iloc[split_idx:]

    metrics = evaluate_portfolio(np.array([1.0]), pd.DataFrame(test_returns), RISK_FREE_RATE)
    return {
        'Algorithm': 'S&P 500',
        'Mean Return': metrics['Mean Return'],
        'Volatility': metrics['Volatility'],
        'Sharpe Ratio': metrics['Sharpe Ratio'],
        'Max Drawdown': metrics['Max Drawdown'],
        'Computation Time (s)': 0,
        'Scenario': 'Benchmark'
    }


# ======================== SCENARIO RUNNER ========================
def run_all_algorithms():
    all_results = []

    # Force only Base Case scenario
    label, tickers, start_date = ('Base Case: 5Y - 5 Stocks',
                                  ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'],
                                  '2019-01-01')

    print(f"\n=== Running ONLY Base Case scenario ===")

    # Benchmark
    benchmark_result = run_benchmark()
    all_results.append(benchmark_result)

    # Mean-Variance
    print("\nRunning Mean-Variance Optimization...")
    mv_result = run_mean_variance_for_scenario(label, tickers, start_date)
    mv_result['Algorithm'] = 'Mean-Variance'
    all_results.append(mv_result)

    # Genetic Algorithm
    print("\nRunning Genetic Algorithm...")
    ga_result = run_ga_for_scenario(tickers, start_date, label)
    ga_result['Algorithm'] = 'Genetic Algorithm'
    all_results.append(ga_result)

    # Ant Colony
    print("\nRunning Ant Colony Optimization...")
    aco_result = run_aco_for_scenario(tickers, start_date, label)
    aco_result['Algorithm'] = 'Ant Colony'
    all_results.append(aco_result)

    # Reinforcement Learning
    print("\nRunning Reinforcement Learning...")
    rl_result = run_dqn_scenario(tickers, start_date, label)
    rl_result['Algorithm'] = 'Reinforcement Learning'
    all_results.append(rl_result)

    return pd.DataFrame(all_results)

# ======================== RESULT DISPLAY ========================
def display_results(results_df):
    print("\n\n=== Portfolio Optimization Results (Base Case) vs Benchmark ===")
    print(results_df[['Algorithm', 'Mean Return', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']]
          .round(4).to_string(index=False))

# ======================== MAIN EXECUTION ========================
if __name__ == "__main__":
    results = run_all_algorithms()
    display_results(results)