# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f077p2y7dXXWSSSZO-QOE9waR5CDYf4Y
"""

# -*- coding: utf-8 -*-
"""Portfolio Optimization Comparison"""

import yfinance as yf
import numpy as np
import pandas as pd
import tensorflow
import time

# Import all algorithm implementations
from mean_variance_optimization import run_mean_variance_for_scenario
from geneticalgorithm import run_ga_for_scenario
from heuristic_model import run_aco_for_scenario
from reinforcement_learning import run_dqn_scenario

# ======================== CONFIGURATION ========================
RISK_FREE_RATE = 0.02
TRAIN_TEST_SPLIT = 0.8
BENCHMARK = '^GSPC'  # S&P 500 benchmark
START_DATE = '2019-01-01'
END_DATE = '2024-01-01'

# Only keep the Base Case scenario
SCENARIOS = [
    ('Base Case: 5Y - 5 Stocks', ['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM'], '2019-01-01')
]

import threading

class TimeoutThread(threading.Thread):
    def __init__(self, target, args=()):
        super().__init__()
        self.target = target
        self.args = args
        self.result = None
        self.exception = None

    def run(self):
        try:
            self.result = self.target(*self.args)
        except Exception as e:
            self.exception = e

    def get_result(self):
        if self.exception:
            raise self.exception
        return self.result
# ======================== BENCHMARK CODE ========================
def evaluate_portfolio(weights, returns, risk_free_rate):
    """Evaluate portfolio performance metrics"""
    daily_port_returns = returns @ weights
    mean_return = np.mean(daily_port_returns) * 252
    variance = np.var(daily_port_returns) * 252
    volatility = np.std(daily_port_returns) * np.sqrt(252)
    sharpe_ratio = (mean_return - risk_free_rate) / (volatility + 1e-8)
    cumulative_returns = (1 + daily_port_returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    return {
        'Mean Return': mean_return,
        'Variance': variance,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown': drawdown.min()
    }

def run_benchmark():
    """Run benchmark (S&P 500) analysis"""
    print("\nDownloading S&P 500 benchmark data...")
    benchmark_data = yf.download(BENCHMARK, start=START_DATE, end=END_DATE)['Close'].dropna()
    benchmark_returns = benchmark_data.pct_change().dropna()
    split_idx = int(len(benchmark_returns) * TRAIN_TEST_SPLIT)
    test_returns = benchmark_returns.iloc[split_idx:]

    metrics = evaluate_portfolio(np.array([1.0]), pd.DataFrame(test_returns), RISK_FREE_RATE)
    return {
        'Algorithm': 'S&P 500',
        'Mean Return': metrics['Mean Return'],
        'Volatility': metrics['Volatility'],
        'Sharpe Ratio': metrics['Sharpe Ratio'],
        'Max Drawdown': metrics['Max Drawdown'],
        'Computation Time (s)': 0,
        'Scenario': 'Benchmark'
    }


# ======================== SCENARIO RUNNER ========================
def run_all_algorithms(label, tickers, start_date):
    all_results = []

    # Override safeguard: allow only Base Case execution
    if "Time Comparison" in label or "Stock Comparison" in label or "Base Case" not in label:
        print(f"\n[OVERRIDDEN] Scenario '{label}' is not the Base Case. Skipping execution.")
        return pd.DataFrame()

    print(f"\n=== Running Base Case scenario: {label} ===")

    # Benchmark
    benchmark_result = run_benchmark()
    all_results.append(benchmark_result)

    # Mean-Variance
    print("\nRunning Mean-Variance Optimization...")
    mv_result = run_mean_variance_for_scenario(label, tickers, start_date)
    mv_result['Algorithm'] = 'Mean-Variance'
    all_results.append(mv_result)

    # Genetic Algorithm
    print("\nRunning Genetic Algorithm...")
    ga_result = run_ga_for_scenario(tickers, start_date, label)
    ga_result['Algorithm'] = 'Genetic Algorithm'
    all_results.append(ga_result)

    # Ant Colony
    print("\nRunning Ant Colony Optimization...")
    aco_result = run_aco_for_scenario(tickers, start_date, label)
    aco_result['Algorithm'] = 'Ant Colony'
    all_results.append(aco_result)

    # Reinforcement Learning
    print("\nRunning Reinforcement Learning...")
    rl_result = run_dqn_scenario(tickers, start_date, label)
    rl_result['Algorithm'] = 'Reinforcement Learning'
    all_results.append(rl_result)

    return pd.DataFrame(all_results)

# ======================== RESULT DISPLAY ========================
def display_results(results_df):
    if results_df.empty:
        print("\n[INFO] No results to display (comparison case was skipped).")
        return

    print("\n\n=== Portfolio Optimization Results (Base Case) vs Benchmark ===")
    print(results_df[['Algorithm', 'Mean Return', 'Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']]
          .round(4).to_string(index=False))

# ======================== MAIN EXECUTION ========================
# ======================== MAIN EXECUTION ========================
if __name__ == "__main__":
    all_final_results = []

    for label, tickers, start_date in SCENARIOS:
        # Always skip non-base case scenarios
        if "Time Comparison" in label or "Stock Comparison" in label or "Base Case" not in label:
            print(f"\n[OVERRIDDEN] Scenario '{label}' is not the Base Case. Skipping execution.")
            continue

        # Timeout execution of all algorithms in the Base Case
        execution_thread = TimeoutThread(target=run_all_algorithms, args=(label, tickers, start_date))
        execution_thread.start()
        execution_thread.join(timeout=4800)  # ⏱️ 1 hour 20 mins = 4800 seconds

        if execution_thread.is_alive():
            print(f"\n[TIMEOUT] Full algorithm execution for scenario '{label}' exceeded 1 hour 20 minutes. Skipping results.")
        else:
            try:
                results = execution_thread.get_result()
                display_results(results)
                all_final_results.append(results)
            except Exception as e:
                print(f"\n[ERROR] Execution failed for scenario '{label}': {e}")

    # Combine all results if any
    if all_final_results:
        combined_df = pd.concat(all_final_results, ignore_index=True)

        # ✅ Final comparison table of all algorithms (including benchmark)
        print("\n\n=== Final Comparison Table: All Algorithms vs Benchmark ===")
        print(combined_df[['Algorithm', 'Scenario', 'Mean Return', 'Variance', 'Volatility',
                           'Sharpe Ratio', 'Max Drawdown', 'Computation Time (s)']]
              .round(4)
              .to_string(index=False))
    else:
        print("\n[INFO] No algorithms completed execution.")
